### ISSUE TITLE
Tracking renamed sections

### ISSUE THREAD

**Issue by lahwaacz** [lahwaacz/wiki-scripts#36]
For use in `link-checker.py`
- [x] wait for general database framework (#35) 
- [x] wait for general parser cache framework (#42) 
- [ ] create custom tables in the database specific to this issue
- [ ] fetching the content of all revisions of a page
- [ ] parsing revision diffs and detecting changes
